# Analysis of Inference Results

This notebook analyzes the CSV results generated by `run_inference.py`.
It calculates metrics (Recall, Accuracy, F1) and displays confusion matrices.

In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, precision_recall_fscore_support
import os

In [2]:
# Configuration
RESULT_DIR = 'result'
RUN_DATE = '0426'
RUN_INDEX = 173
MODEL_NAME = 'secbert'

# Construct filenames based on inference script naming convention
file_prefix = f'result/{MODEL_NAME}_{RUN_DATE}_{RUN_INDEX}_result'

print(f'Reading results from prefix: {file_prefix}')

Reading results from prefix: result/secbert_0426_173_result


In [3]:
# Load Results
try:
    time_result = pd.read_csv(f'{file_prefix}_time.csv')
    tag_result = pd.read_csv(f'{file_prefix}_tag.csv')
    scale_result = pd.read_csv(f'{file_prefix}_scale.csv')
    negative_result = pd.read_csv(f'{file_prefix}_negative.csv')
    
    # Optional: Load Fact result if available
    fact_path = f'{file_prefix}_fact.csv'
    if os.path.exists(fact_path):
        fact_result = pd.read_csv(fact_path)
    else:
        fact_result = None
        
    print('✅ Loaded all result CSVs.')
except FileNotFoundError as e:
    print(f'❌ Error loading files: {e}')
    print('Please ensure run_inference.py has finished successfully.')

✅ Loaded all result CSVs.


In [4]:
def print_metrics(df, attr_name, true_col=None, pred_col=None):
    if df is None:
        print(f'No data for {attr_name}')
        return
        
    print(f'\{attr_name.upper()} Classification Metrics:')
    if true_col is None: true_col = f'true_{attr_name}'
    if pred_col is None: pred_col = f'pred_{attr_name}'
    
    y_true = df[true_col]
    y_pred = df[pred_col]
    
    acc = accuracy_score(y_true, y_pred)
    precision_w, recall_w, f1_w, _ = precision_recall_fscore_support(y_true, y_pred, average='weighted', zero_division=0)
    precision_m, recall_m, f1_m, _ = precision_recall_fscore_support(y_true, y_pred, average='macro', zero_division=0)
    
    print(f'Accuracy: {acc:.4f}')
    print(f'Precision (weighted): {precision_w:.4f}, (macro): {precision_m:.4f}')
    print(f'Recall (weighted): {recall_w:.4f}, (macro): {recall_m:.4f}')
    print(f'F1 Score (weighted): {f1_w:.4f}, (macro): {f1_m:.4f}')
    
    print('Confusion Matrix:')
    print(confusion_matrix(y_true, y_pred))
    
    print('Classification Report:')
    print(classification_report(y_true, y_pred, zero_division=0))

In [5]:
# Analyze TIME
print_metrics(time_result, 'time')

\TIME Classification Metrics:
Accuracy: 0.7053
Precision (weighted): 0.7029, (macro): 0.4853
Recall (weighted): 0.7053, (macro): 0.4112
F1 Score (weighted): 0.6963, (macro): 0.4325
Confusion Matrix:
[[    0    60    44    35    61    52     0    15     0     0]
 [    0 11623  2600     9  2154   315     6    35     0     0]
 [    0  2349 19362    86   714  1317    51   233     0     0]
 [    0   111   660  1363    70   138    39     5     0     0]
 [    0  1491   630     4 17474  1583    37   295     0     0]
 [    0   310  1792     7  2063 10185    95   726     0     0]
 [    0    37   203    12   215   586   205    24     0     0]
 [    0   200  1173     5  1658  2196    18  3502     0     0]
 [    0     0     4     0     2    25     2     6     0     0]
 [    0     3     9     0    17    30     3     3     0     0]]
Classification Report:
              precision    recall  f1-score   support

        -100       0.00      0.00      0.00       267
           0       0.72      0.69     

In [6]:
# Analyze SCALE
print_metrics(scale_result, 'scale')

\SCALE Classification Metrics:
Accuracy: 0.8940
Precision (weighted): 0.8329, (macro): 0.3343
Recall (weighted): 0.8940, (macro): 0.3597
F1 Score (weighted): 0.8588, (macro): 0.3454
Confusion Matrix:
[[    0     0     0     0    54     0  7366     0   298     0     0    36
      0     0     0     0]
 [    0     0     0     0     1     0     0     0     0     0     0     0
      0     0     0     0]
 [    0     0   184     0    13     0     3     0     0     0     0     1
      0     0     0     0]
 [    0     0     2     0     1     0     4     0     0     0     0     0
      0     0     0     0]
 [    0     0    22     0 14399     0    68     0     5     0     0    15
      0     0     0     0]
 [    0     0     0     0     4     0     0     0     0     0     0     0
      0     0     0     0]
 [    0     0    16     0   119     0 18704     0   397     0     0   105
      0     0     0     0]
 [    0     0     0     0     1     0     0     0     0     0     0     0
      0     0     0

In [7]:
# Analyze NEGATIVE
print_metrics(negative_result, 'negative')

\NEGATIVE Classification Metrics:
Accuracy: 0.9744
Precision (weighted): 0.9640, (macro): 0.5711
Recall (weighted): 0.9744, (macro): 0.5730
F1 Score (weighted): 0.9692, (macro): 0.5721
Confusion Matrix:
[[    0   945     6]
 [    0 86185   668]
 [    0   692  1841]]
Classification Report:
              precision    recall  f1-score   support

        -100       0.00      0.00      0.00       951
           0       0.98      0.99      0.99     86853
           1       0.73      0.73      0.73      2533

    accuracy                           0.97     90337
   macro avg       0.57      0.57      0.57     90337
weighted avg       0.96      0.97      0.97     90337



In [8]:
# Analyze TAG
print_metrics(tag_result, 'tag')

\TAG Classification Metrics:
Accuracy: 0.6930
Precision (weighted): 0.6885, (macro): 0.5833
Recall (weighted): 0.6930, (macro): 0.5177
F1 Score (weighted): 0.6829, (macro): 0.5224
Confusion Matrix:
[[18791  1540    78 ...     0     0     0]
 [ 1799  5134    21 ...     0     0     0]
 [   38    10  1507 ...     0     0     0]
 ...
 [    3     0     0 ...     6     0     0]
 [    5     5     0 ...     0     1     0]
 [    4     0     0 ...     0     0     2]]
Classification Report:
              precision    recall  f1-score   support

           0       0.74      0.76      0.75     24644
           1       0.61      0.56      0.58      9175
           2       0.85      0.92      0.88      1646
           3       0.85      0.93      0.89      1289
           4       0.62      0.76      0.68      1341
           5       0.72      0.86      0.78      1228
           6       0.75      0.88      0.81      1030
           7       0.90      0.88      0.89       802
           8       0.99     

In [9]:
# Analyze FACT (Regression)
if fact_result is not None:
    print('\FACT Regression Metrics:')
    from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
    
    y_true = fact_result['true_fact']
    y_pred = fact_result['pred_fact']
    
    mse = mean_squared_error(y_true, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_true, y_pred)
    r2 = r2_score(y_true, y_pred)
    
    print(f'MSE: {mse:.4f}')
    print(f'RMSE: {rmse:.4f}')
    print(f'MAE: {mae:.4f}')
    print(f'R² Score: {r2:.4f}')

\FACT Regression Metrics:
MSE: 18970358928373169782784.0000
RMSE: 137732926086.5868
MAE: 1708250336.9920
R² Score: -1.3199


## Save Analysis Output
Per requirement: 'let data analysis output to csv'
We will save a summary of metrics to a CSV file.

In [10]:
metrics_data = []

def get_metrics_dict(df, attr_name):
    if df is None: return None
    y_true = df[f'true_{attr_name}']
    y_pred = df[f'pred_{attr_name}']
    acc = accuracy_score(y_true, y_pred)
    p_w, r_w, f1_w, _ = precision_recall_fscore_support(y_true, y_pred, average='weighted', zero_division=0)
    p_m, r_m, f1_m, _ = precision_recall_fscore_support(y_true, y_pred, average='macro', zero_division=0)
    return {'Task': attr_name, 'Accuracy': acc, 'Precision_Weighted': p_w, 'Recall_Weighted': r_w, 'F1_Weighted': f1_w, 'Precision_Macro': p_m, 'Recall_Macro': r_m, 'F1_Macro': f1_m}

for df, name in [(time_result, 'time'), (scale_result, 'scale'), (negative_result, 'negative'), (tag_result, 'tag')]:
    m = get_metrics_dict(df, name)
    if m: metrics_data.append(m)

metrics_df = pd.DataFrame(metrics_data)
output_csv = f'analysis_metrics_{RUN_DATE}_{RUN_INDEX}.csv' if 'RUN_DATE' in locals() else 'analysis_metrics.csv'
metrics_df.to_csv(output_csv, index=False)
print(f'Saved analysis metrics to {output_csv}')
metrics_df

Saved analysis metrics to analysis_metrics_0426_173.csv


,Task,Accuracy,Precision_Weighted,Recall_Weighted,F1_Weighted,Precision_Macro,Recall_Macro,F1_Macro
0,time,0.705292,0.702904,0.705292,0.696290,0.485344,0.411179,0.432546
1,scale,0.893986,0.832857,0.893986,0.858795,0.334265,0.359658,0.345439
2,negative,0.974418,0.964037,0.974418,0.969198,0.571123,0.573038,0.572067
3,tag,0.692994,0.688466,0.692994,0.682885,0.583253,0.517672,0.522405
